# Creation Date: 2019-06-17
#
# Author: Luca Di Maio
---

# file: main.yml

- hosts: all
  gather_facts: True
  tasks:

  # Role for minimal distro setup
  - include_role:
      name: fedora_minimal
    tags: base_distro, system_tweaks, powersave
