---
# vars file
#

base_packages:
      - "@base-x"
      - "@core"
      - "@firefox"
      - "@fonts"
      - "@hardware-support"
      - "@networkmanager-submodules"
      - "@printing"
      - ModemManager
      - NetworkManager-adsl
      - NetworkManager-config-connectivity-fedora
      - NetworkManager-ppp
      - adwaita-gtk2-theme
      - adwaita-qt4
      - adwaita-qt5
      - alsa-plugins-pulseaudio
      - alsa-ucm
      - alsa-utils
      - earlyoom
      - git
      - glibc-all-langpacks
      - libsane-hpaio
      - pulseaudio-module-x11
      - pulseaudio-utils
      - rp-pppoe
      - usb_modeswitch
      - zram

gnome_user_apps:
      - baobab
      - eog
      - evince
      - evince-djvu
      - evince-nautilus
      - file-roller
      - file-roller-nautilus
      - gedit
      - gnome-calculator
      - gnome-disk-utility
      - gnome-screenshot
      - nautilus
      - nautilus-sendto


gnome_packages:
      - NetworkManager-fortisslvpn-gnome
      - NetworkManager-iodine-gnome
      - NetworkManager-l2tp-gnome
      - NetworkManager-libreswan-gnome
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-ssh-gnome
      - NetworkManager-sstp-gnome
      - NetworkManager-strongswan-gnome
      - NetworkManager-vpnc-gnome
      - avahi
      - chrome-gnome-shell
      - fros-gnome
      - gnome-color-manager
      - gnome-session
      - gnome-session-wayland-session
      - gnome-session-xsession
      - gnome-shell
      - gnome-system-monitor
      - gnome-terminal
      - gnome-terminal-nautilus
      - gnome-themes-extra
      - gnome-tweak-tool
      - gvfs-afc
      - gvfs-afp
      - gvfs-archive
      - gvfs-fuse
      - gvfs-goa
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-smb
      - libcanberra-gtk2
      - libproxy-mozjs
      - nautilus
      - nautilus-sendto
      - qgnomeplatform
      - qt-settings
      - qt5-qtxmlpatterns
      - xdg-user-dirs-gtk

kde_packages:
      - bluedevil
      - breeze-icon-theme
      - colord-kde
      - dolphin
      - gnome-keyring-pam
      - kcm_systemd
      - kde-gtk-config
      - kde-print-manager
      - kde-settings-pulseaudio
      - kdegraphics-thumbnailers
      - kdeplasma-addons
      - kdialog
      - kdnssd
      - kfind
      - kinfocenter
      - konsole5
      - kscreen
      - kscreenlocker
      - kwebkitpart
      - kwin
      - phonon-qt5-backend-gstreamer
      - plasma-breeze
      - plasma-desktop
      - plasma-desktop-doc
      - plasma-drkonqi
      - plasma-nm-l2tp
      - plasma-nm-openconnect
      - plasma-nm-openswan
      - plasma-nm-openvpn
      - plasma-nm-pptp
      - plasma-nm-ssh
      - plasma-nm-vpnc
      - plasma-pa
      - plasma-pk-updates
      - plasma-user-manager
      - plasma-workspace
      - plasma-workspace-geolocation
      - polkit-kde
      - sddm
      - sddm-breeze
      - sddm-kcm
      - system-config-language

phosh_packages:
      - NetworkManager-fortisslvpn-gnome
      - NetworkManager-iodine-gnome
      - NetworkManager-l2tp-gnome
      - NetworkManager-libreswan-gnome
      - NetworkManager-openconnect-gnome
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-ssh-gnome
      - NetworkManager-ssh-gnome
      - NetworkManager-sstp-gnome
      - NetworkManager-strongswan-gnome
      - NetworkManager-vpnc-gnome
      - avahi
      - baobab
      - chrome-gnome-shell
      - eog
      - evince
      - evince-djvu
      - evince-nautilus
      - file-roller
      - file-roller-nautilus
      - fros-gnome
      - gedit
      - gnome-calculator
      - gnome-color-manager
      - gnome-disk-utility
      - gnome-screenshot
      - gnome-system-monitor
      - gnome-terminal
      - gnome-terminal-nautilus
      - gnome-themes-extra
      - gnome-tweak-tool
      - gvfs-afc
      - gvfs-afp
      - gvfs-archive
      - gvfs-fuse
      - gvfs-goa
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-smb
      - libcanberra-gtk2
      - libproxy-mozjs
      - mousetweaks
      - nautilus
      - nautilus-sendto
      - qgnomeplatform
      - qt-settings
      - qt5-qtxmlpatterns
      - xdg-user-dirs-gtk
      - feedbackd
      - phoc
      - phosh
      - squeekboard
      - epiphany

xfce_packages:
      - NetworkManager-fortisslvpn-gnome
      - NetworkManager-iodine-gnome
      - NetworkManager-l2tp-gnome
      - NetworkManager-libreswan-gnome
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-ssh-gnome
      - NetworkManager-sstp-gnome
      - NetworkManager-strongswan-gnome
      - NetworkManager-vpnc-gnome
      - arc-theme
      - blueberry
      - gtk-xfce-engine
      - gvfs-afc
      - gvfs-afp
      - gvfs-archive
      - gvfs-fuse
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-smb
      - lightdm-gtk
      - network-manager-applet
      - nm-connection-editor
      - openssh-askpass
      - papirus-icon-theme
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-vcs-plugin thunar-volman
      - xdg-user-dirs-gtk
      - xfce4-about
      - xfce4-appfinder
      - xfce4-datetime-plugin
      - xfce4-panel
      - xfce4-places-plugin
      - xfce4-power-manager
      - xfce4-pulseaudio-plugin
      - xfce4-screenshooter-plugin
      - xfce4-session
      - xfce4-settings
      - xfce4-volumed
      - xfce4-taskmanager
      - xfce4-terminal
      - xfce4-notifyd
      - xfce4-whiskermenu-plugin
      - xfconf
      - xfdesktop
      - xfwm4
      - xfwm4-themes
      - xscreensaver-base

archive_packages:
      - cabextract
      - lzip
      - p7zip
      - p7zip-plugins
      - unzip

codecs_packages:
      - compat-ffmpeg28
      - compat-ffmpeg28-devel
      - ffmpeg
      - ffmpeg-libs
      - gstreamer1-libav
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-base
      - gstreamer1-plugins-base-tools
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-ugly-free
      - gstreamer1-svt-av1
      - gstreamer1-svt-vp9
      - gstreamer1-vaapi
      - intel-media-driver
      - libva-devel
      - libva-intel-driver
      - libva-intel-hybrid-driver
      - libva-utils
      - libva-vdpau-driver
      - libvdpau-va-gl

global_vars:
      - export MOZ_ACCELLERATED=1
      - export MOZ_USE_XINPUT2=1
      - export MOZ_WEBRENDER=1
      - export MOZ_X11_EGL=1
      - export QT_QPA_PLATFORM=xcb
