---
# Create base distro from minimal fedora netinstall
#

- name: Update packages
  command: |
    dnf update -y
  become: true
  tags: base_distro

- name: Build up base distro
  include: minimal_distro.yml
  tags: base_distro

- name: Performance Tweaks
  include: system_tweaks.yml
  tags: never, system_tweaks

- name: Powersaving Tweaks
  include: powersave.yml
  tags: never, powersave
