---
# Create base distro from minimal fedora netinstall
#

- name: Update packages
  command: |
    dnf update -y
  become: true
  tags: base_distro

- name: Build up base distro
  include: minimal_distro.yml
  tags: base_distro

- name: Performance Tweaks
  include: system_tweaks.yml
  tags: system_tweaks

- name: Powersaving Tweaks
  include: powersave.yml
  tags: powersave

- name: Install gnome packages
  dnf:
    name: "{{ gnome_packages }}"
  become: true
  tags: never,gnome

- name: Install phosh packages
  dnf:
    name: "{{ phosh_packages }}"
  become: true
  tags: never,phosh

- name: Install kde packages
  dnf:
    name: "{{ kde_packages }}"
  become: true
  tags: never,kde

- name: Install xfce packages
  dnf:
    name: "{{ xfce_packages }}"
  become: true
  tags: never,xfce

  ############################# REBOOT #######################################

- name: Base distro ready, reboot and continue
  reboot:
  become: true
  tags: reboot
