---
# Create base distro from minimal fedora netinstall
#

- name: Update packages
  dnf:
    name: "*"
    state: latest
  become: yes
  tags: base_distro

- name: Build up base distro
  include: minimal_distro.yml
  tags: base_distro

- name: Performance Tweaks
  include: system_tweaks.yml
  tags: system_tweaks

- name: Powersaving Tweaks
  include: powersave.yml
  tags: never,powersave

- name: Install xorg base packages
  dnf:
    name: "{{ xorg_packages }}"
  become: yes
  tags: never,gnome,xfce,lxde,kde

- name: Install gnome base packages
  dnf:
    name: "{{ gtk_base_packaged }}"
  become: yes
  tags: never,gnome,xfce,lxde

- name: Install gnome packages
  dnf:
    name: "{{ gnome_packages }}"
  become: yes
  tags: never,gnome

- name: Install kde packages
  dnf:
    name: "{{ kde_packages }}"
  become: yes
  tags: never,kde

- name: Install xfce packages
  dnf:
    name: "{{ xfce_packages }}"
  become: yes
  tags: never,xfce

- name: Install lxde packages
  dnf:
    name: "{{ lxde_packages }}"
  become: yes
  tags: never,lxde

- name: Hardening Tweaks
  include: hardening.yml
  tags: never,hardening

  ############################# REBOOT #######################################

- name: Base distro ready, reboot and continue
  reboot:
  become: yes
  tags: reboot

...
